# This is workflow is for MSI and deploy to artifactory. 
name: autorostering-msi-build

on:
  workflow_dispatch:
    inputs:
      auto-rostering-environment:
        description: 'Environment'
        required: true
        default: 'Development'
        type: choice
        options:
        - Development
        - Production
      release-version:
        description: 'Release version'
        required: true
        default: '1.3.0.0'
        type: choice
        options:
        - '1.3.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Publish setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: AutoRosteringSetup
        path: ./AutoRosteringSetup

  msi_build:
    runs-on: windows-latest
    needs: build
    
    steps:      
    - uses: actions/checkout@v3

    - name: Publish setup artifact
      uses: actions/upload-artifact@v2
      with:
        name: AutoRostering_${{ github.event.inputs.release-version }}_${{ github.event.inputs.auto-rostering-environment }}.cs
        path: ${{github.workspace}}/CustomAction/CustomAction.cs
        
  publish_build:
    runs-on: ubuntu-latest
    needs: msi_build
    
    steps:
    - uses: actions/checkout@v3

    - name: Delete artifacts
      uses: actions/delete-artifact@v2
      with:
        name: | 
          AutoRosteringSetup
          AutoRostering_${{ github.event.inputs.release-version }}_${{ github.event.inputs.auto-rostering-environment }}.cs