on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/autorostering_msi.yaml'
  pull_request:
    branches: [ main ]

env:
  DAY_OF_WEEK: Monday
  MONTH_JAN: January
  MONTH_FEB: February
  MONTH_MAR: March

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:      
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: "Hi, Ravi today is _______"
      run: |
        echo "Hi, Ravi today is $DAY_OF_WEEK!"
        echo "Hi, Ravi month is $MONTH_JAN!"

  build2:

    runs-on: ubuntu-latest
    needs: build
    steps:      
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: "Hi, build2 today is _______"
      run: |
        echo "Hi, build2 today is $DAY_OF_WEEK!"
        echo "Hi, build2 month is $MONTH_FEB!"

  build3:

    runs-on: ubuntu-latest
    needs: build2
    steps:      
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: "Hi, build3 today is _______"
      run: |
        echo "Hi, build3 today is $DAY_OF_WEEK!"
        echo "Hi, build3 month is $MONTH_MAR!"

    # - name: convert to utf-8
    #   working-directory: ./WEB/Backend/ESolve/ESolve
    #   run: sed -i '1s/^\xEF\xBB\xBF//' migrations.sql

    # - name: Copy files to root and create AR folder
    #   run: |
    #     mkdir AutoRostering
    #     mkdir AutoRostering/api
    #     cp -r ./WEB/Backend/ESolve/ESolve/bin/Release/net6.0/* ./AutoRostering/api/
    #     cp -r ./WEB/Backend/ESolve/ESolve/migrations.sql ./AutoRostering/
    #     cp -r ./WEB/Frontend/dist/* ./AutoRostering/
        
    # - name: setup .net core
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 6.0.x

    # - name: Build MSI
    #   working-directory: ${{github.workspace}}
    #   run: dotnet build AutoRosteringSetup.sln -c Release -p:Platform=x64 -p:Build_Number=21901 -p:VisualStudioVersion=17.0
  
    # - name: Copy files to root and create AR folder
    #   run: |
    #     mkdir AutoRostering
    #     mkdir AutoRostering/api
    #     cp -r ./WEB/Backend/ESolve/ESolve/bin/Release/net6.0/* ./AutoRostering/api/
    #     cp -r ./WEB/Backend/ESolve/ESolve/migrations.sql ./AutoRostering/
    #     cp -r ./WEB/Frontend/dist/* ./AutoRostering/
      
    # - name: Setup MS Build
    #   uses: microsoft/setup-msbuild@v1.1
      
    # - name: Setup NuGet
    #   uses: NuGet/setup-nuget@v1.0.5 

    # - name: Restore NuGet packages
    #   working-directory: ${{github.workspace}}
    #   run: nuget restore AutoRosteringSetup.sln
      
    # - name: Build AR msi
    #   working-directory: ${{github.workspace}}
    #   run: msbuild AutoRosteringSetup.sln -t:build -verbosity:diag -property:Configuration=Release -p:Platform=x64 -p:Build_Number=21901 -p:VisualStudioVersion=17.0 